FROM node:alpine AS build

WORKDIR /workdir

COPY package*.json .

RUN npm i

COPY src src

COPY tsconfig.json .

RUN npm run build

FROM fedora:rawhide

WORKDIR /app

RUN dnf install -y chromium-browser nodejs sqlite sqlite-devel xorg-x11-server-Xvfb x11vnc && \
    dnf clean all && \
    rm -rf /var/cache/dnf /var/log/dnf.*

COPY package*.json .

RUN npm ci 

COPY --from=build /workdir/dist/* ./ 

COPY ./startup.sh  ./

RUN chmod +x startup.sh

CMD ["/app/startup.sh"]

EXPOSE 5900

