// /** Declaration file generated by dts-gen */

// declare module "xvfb" {
//   class xvfb {
//     constructor(options: {
//       displayNum?: number | string;
//       reuse?: boolean;
//       timeout?: number;
//       silent?: boolean;
//       xvfb_args?: string[];
//     });

//     // display(): any;

//     // start(cb: any): void;

//     startSync(): { pid: number };

//     // stop(cb: any): any;

//     stopSync(): void;
//   }

//   export default xvfb;
// }
